# Twitter API configuration
TWITTER_CONSUMER_KEY = 'INSERT_VALUE_HERE'
TWITTER_CONSUMER_SECRET = 'INSERT_VALUE_HERE'
TWITTER_ACCESS_TOKEN = 'INSERT_VALUE_HERE'
TWITTER_ACCESS_TOKEN_SECRET = 'INSERT_VALUE_HERE'

# We add a little fuzz because we're not in that much of a hurry
TWITTER_API_FUZZ = 1.5

TWITTER_API_DELAY = 1.0/(180.0 * 4.0/3600.0) * TWITTER_API_FUZZ
